vich_uploader:
    db_driver: orm

    mappings:
        lesson_images:
            uri_prefix: '%lesson_images%'
            upload_destination: '%kernel.project_dir%/public%lesson_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
             
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            